-- A 股量化数据平台 Rho：收入对账、账单重算、AR aging 和客户健康

CREATE TABLE IF NOT EXISTS qmeta.revenue_reconciliation_run (
    reconciliation_id        BIGSERIAL PRIMARY KEY,
    reconciliation_code      VARCHAR(200) NOT NULL UNIQUE,
    tenant_id                BIGINT NOT NULL REFERENCES qmeta.tenant(tenant_id),
    project_id               BIGINT REFERENCES qmeta.project(project_id),
    subscription_id          BIGINT REFERENCES qmeta.product_subscription(subscription_id),
    plan_id                  BIGINT REFERENCES qmeta.pricing_plan(plan_id),
    product_id               BIGINT REFERENCES qmeta.data_product(product_id),
    invoice_id               BIGINT REFERENCES qmeta.invoice(invoice_id) ON DELETE SET NULL,
    period_start             DATE NOT NULL,
    period_end               DATE NOT NULL,
    reconciliation_date      DATE NOT NULL DEFAULT CURRENT_DATE,
    currency                 VARCHAR(16) NOT NULL DEFAULT 'CNY',
    status                   VARCHAR(32) NOT NULL DEFAULT 'matched',
    tolerance_amount         NUMERIC(24, 8) NOT NULL DEFAULT 0.00000001,
    recomputed_subtotal_amount NUMERIC(24, 8) NOT NULL DEFAULT 0,
    recomputed_total_amount  NUMERIC(24, 8) NOT NULL DEFAULT 0,
    invoice_subtotal_amount  NUMERIC(24, 8) NOT NULL DEFAULT 0,
    invoice_total_amount     NUMERIC(24, 8) NOT NULL DEFAULT 0,
    amount_delta             NUMERIC(24, 8) NOT NULL DEFAULT 0,
    invoice_paid_amount      NUMERIC(24, 8) NOT NULL DEFAULT 0,
    invoice_outstanding_amount NUMERIC(24, 8) NOT NULL DEFAULT 0,
    recomputed_line_count    INTEGER NOT NULL DEFAULT 0,
    invoice_line_count       INTEGER NOT NULL DEFAULT 0,
    matched_line_count       INTEGER NOT NULL DEFAULT 0,
    mismatch_line_count      INTEGER NOT NULL DEFAULT 0,
    missing_line_count       INTEGER NOT NULL DEFAULT 0,
    extra_line_count         INTEGER NOT NULL DEFAULT 0,
    request_count            BIGINT NOT NULL DEFAULT 0,
    row_count                BIGINT NOT NULL DEFAULT 0,
    cost_units               NUMERIC(24, 8) NOT NULL DEFAULT 0,
    details                  JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (period_end >= period_start),
    CHECK (status IN ('matched', 'mismatch', 'missing_invoice', 'warning')),
    CHECK (tolerance_amount >= 0),
    CHECK (recomputed_subtotal_amount >= 0),
    CHECK (recomputed_total_amount >= 0),
    CHECK (invoice_subtotal_amount >= 0),
    CHECK (invoice_total_amount >= 0),
    CHECK (invoice_paid_amount >= 0),
    CHECK (invoice_outstanding_amount >= 0),
    CHECK (recomputed_line_count >= 0),
    CHECK (invoice_line_count >= 0),
    CHECK (matched_line_count >= 0),
    CHECK (mismatch_line_count >= 0),
    CHECK (missing_line_count >= 0),
    CHECK (extra_line_count >= 0),
    CHECK (request_count >= 0),
    CHECK (row_count >= 0),
    CHECK (cost_units >= 0)
);

CREATE INDEX IF NOT EXISTS idx_revenue_reconciliation_lookup
    ON qmeta.revenue_reconciliation_run(tenant_id, project_id, product_id, period_start DESC, period_end DESC);

CREATE INDEX IF NOT EXISTS idx_revenue_reconciliation_status
    ON qmeta.revenue_reconciliation_run(status, reconciliation_date DESC, amount_delta);

CREATE TABLE IF NOT EXISTS qmeta.revenue_reconciliation_line (
    line_reconciliation_id   BIGSERIAL PRIMARY KEY,
    reconciliation_id        BIGINT NOT NULL REFERENCES qmeta.revenue_reconciliation_run(reconciliation_id) ON DELETE CASCADE,
    invoice_line_id          BIGINT REFERENCES qmeta.invoice_line(line_id) ON DELETE SET NULL,
    line_key                 VARCHAR(220) NOT NULL,
    api_name                 VARCHAR(128),
    metric_name              VARCHAR(32) NOT NULL,
    product_id               BIGINT REFERENCES qmeta.data_product(product_id),
    pricing_rule_id          BIGINT REFERENCES qmeta.pricing_rule(rule_id) ON DELETE SET NULL,
    status                   VARCHAR(32) NOT NULL DEFAULT 'matched',
    recomputed_quantity      NUMERIC(24, 8) NOT NULL DEFAULT 0,
    invoice_quantity         NUMERIC(24, 8) NOT NULL DEFAULT 0,
    quantity_delta           NUMERIC(24, 8) NOT NULL DEFAULT 0,
    recomputed_amount        NUMERIC(24, 8) NOT NULL DEFAULT 0,
    invoice_amount           NUMERIC(24, 8) NOT NULL DEFAULT 0,
    amount_delta             NUMERIC(24, 8) NOT NULL DEFAULT 0,
    request_count            BIGINT NOT NULL DEFAULT 0,
    row_count                BIGINT NOT NULL DEFAULT 0,
    cost_units               NUMERIC(24, 8) NOT NULL DEFAULT 0,
    details                  JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (reconciliation_id, line_key),
    CHECK (metric_name IN ('request', 'row', 'cost_unit', 'export', 'monthly_fee', 'base_fee', 'adjustment')),
    CHECK (status IN ('matched', 'mismatch', 'missing_invoice_line', 'extra_invoice_line')),
    CHECK (recomputed_quantity >= 0),
    CHECK (invoice_quantity >= 0),
    CHECK (recomputed_amount >= 0),
    CHECK (invoice_amount >= 0),
    CHECK (request_count >= 0),
    CHECK (row_count >= 0),
    CHECK (cost_units >= 0)
);

CREATE INDEX IF NOT EXISTS idx_revenue_reconciliation_line_status
    ON qmeta.revenue_reconciliation_line(reconciliation_id, status, amount_delta);

CREATE TABLE IF NOT EXISTS qmeta.ar_aging_snapshot (
    aging_id                 BIGSERIAL PRIMARY KEY,
    aging_code               VARCHAR(200) NOT NULL UNIQUE,
    tenant_id                BIGINT NOT NULL REFERENCES qmeta.tenant(tenant_id),
    project_id               BIGINT REFERENCES qmeta.project(project_id),
    product_id               BIGINT REFERENCES qmeta.data_product(product_id),
    plan_id                  BIGINT REFERENCES qmeta.pricing_plan(plan_id),
    as_of_date               DATE NOT NULL,
    currency                 VARCHAR(16) NOT NULL DEFAULT 'CNY',
    status                   VARCHAR(24) NOT NULL DEFAULT 'current',
    invoice_count            INTEGER NOT NULL DEFAULT 0,
    overdue_invoice_count    INTEGER NOT NULL DEFAULT 0,
    outstanding_amount       NUMERIC(24, 8) NOT NULL DEFAULT 0,
    current_amount           NUMERIC(24, 8) NOT NULL DEFAULT 0,
    bucket_1_30_amount       NUMERIC(24, 8) NOT NULL DEFAULT 0,
    bucket_31_60_amount      NUMERIC(24, 8) NOT NULL DEFAULT 0,
    bucket_61_90_amount      NUMERIC(24, 8) NOT NULL DEFAULT 0,
    bucket_90_plus_amount    NUMERIC(24, 8) NOT NULL DEFAULT 0,
    max_days_past_due        INTEGER NOT NULL DEFAULT 0,
    details                  JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, project_id, product_id, plan_id, currency, as_of_date),
    CHECK (status IN ('current', 'watch', 'overdue', 'critical')),
    CHECK (invoice_count >= 0),
    CHECK (overdue_invoice_count >= 0),
    CHECK (outstanding_amount >= 0),
    CHECK (current_amount >= 0),
    CHECK (bucket_1_30_amount >= 0),
    CHECK (bucket_31_60_amount >= 0),
    CHECK (bucket_61_90_amount >= 0),
    CHECK (bucket_90_plus_amount >= 0),
    CHECK (max_days_past_due >= 0)
);

CREATE INDEX IF NOT EXISTS idx_ar_aging_snapshot_status
    ON qmeta.ar_aging_snapshot(status, as_of_date DESC, outstanding_amount DESC);

CREATE TABLE IF NOT EXISTS qmeta.customer_health_snapshot (
    health_id                BIGSERIAL PRIMARY KEY,
    health_code              VARCHAR(220) NOT NULL UNIQUE,
    tenant_id                BIGINT NOT NULL REFERENCES qmeta.tenant(tenant_id),
    project_id               BIGINT REFERENCES qmeta.project(project_id),
    subscription_id          BIGINT REFERENCES qmeta.product_subscription(subscription_id),
    product_id               BIGINT REFERENCES qmeta.data_product(product_id),
    plan_id                  BIGINT REFERENCES qmeta.pricing_plan(plan_id),
    as_of_date               DATE NOT NULL,
    status                   VARCHAR(24) NOT NULL DEFAULT 'active',
    retention_signal         VARCHAR(32) NOT NULL DEFAULT 'healthy',
    health_score             INTEGER NOT NULL DEFAULT 100,
    last_usage_date          DATE,
    days_since_last_usage    INTEGER,
    request_count_7d         BIGINT NOT NULL DEFAULT 0,
    request_count_30d        BIGINT NOT NULL DEFAULT 0,
    request_count_90d        BIGINT NOT NULL DEFAULT 0,
    cost_units_30d           NUMERIC(24, 8) NOT NULL DEFAULT 0,
    invoice_count_90d        INTEGER NOT NULL DEFAULT 0,
    paid_amount_90d          NUMERIC(24, 8) NOT NULL DEFAULT 0,
    total_amount_90d         NUMERIC(24, 8) NOT NULL DEFAULT 0,
    outstanding_amount       NUMERIC(24, 8) NOT NULL DEFAULT 0,
    overdue_amount           NUMERIC(24, 8) NOT NULL DEFAULT 0,
    overdue_invoice_count    INTEGER NOT NULL DEFAULT 0,
    details                  JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (subscription_id, as_of_date),
    CHECK (status IN ('active', 'at_risk', 'dormant', 'churned')),
    CHECK (retention_signal IN ('healthy', 'payment_risk', 'usage_declining', 'inactive', 'no_usage')),
    CHECK (health_score >= 0 AND health_score <= 100),
    CHECK (days_since_last_usage IS NULL OR days_since_last_usage >= 0),
    CHECK (request_count_7d >= 0),
    CHECK (request_count_30d >= 0),
    CHECK (request_count_90d >= 0),
    CHECK (cost_units_30d >= 0),
    CHECK (invoice_count_90d >= 0),
    CHECK (paid_amount_90d >= 0),
    CHECK (total_amount_90d >= 0),
    CHECK (outstanding_amount >= 0),
    CHECK (overdue_amount >= 0),
    CHECK (overdue_invoice_count >= 0)
);

CREATE INDEX IF NOT EXISTS idx_customer_health_snapshot_status
    ON qmeta.customer_health_snapshot(status, as_of_date DESC, health_score);
