-- A 股量化数据平台 Zeta-3：真实供应商接入运营化

CREATE TABLE IF NOT EXISTS qmeta.vendor_onboarding_run (
    run_id                    BIGSERIAL PRIMARY KEY,
    run_code                  VARCHAR(180) NOT NULL UNIQUE,
    source_id                 BIGINT NOT NULL REFERENCES qmeta.source_system(source_id),
    profile_id                BIGINT REFERENCES qmeta.vendor_integration_profile(profile_id) ON DELETE SET NULL,
    primary_source_id         BIGINT REFERENCES qmeta.source_system(source_id),
    requested_by              VARCHAR(128) NOT NULL DEFAULT 'zeta3',
    trigger_mode              VARCHAR(32) NOT NULL DEFAULT 'manual',
    environment               VARCHAR(32) NOT NULL DEFAULT 'local',
    status                    VARCHAR(32) NOT NULL DEFAULT 'planned',
    preflight_status          VARCHAR(32) NOT NULL DEFAULT 'planned',
    canary_status             VARCHAR(32) NOT NULL DEFAULT 'planned',
    gate_status               VARCHAR(32) NOT NULL DEFAULT 'planned',
    orchestration_status      VARCHAR(32) NOT NULL DEFAULT 'planned',
    recommendation            VARCHAR(32) NOT NULL DEFAULT 'research_only',
    recommended_role          VARCHAR(32) NOT NULL DEFAULT 'research_only',
    dataset_codes             TEXT[] NOT NULL DEFAULT '{}',
    canary_symbols            TEXT[] NOT NULL DEFAULT '{}',
    required_windows          INTEGER[] NOT NULL DEFAULT ARRAY[5, 20, 60],
    shard_size                INTEGER NOT NULL DEFAULT 500,
    max_symbols               INTEGER,
    allow_live                BOOLEAN NOT NULL DEFAULT FALSE,
    require_live              BOOLEAN NOT NULL DEFAULT FALSE,
    require_active_profile    BOOLEAN NOT NULL DEFAULT TRUE,
    require_contract          BOOLEAN NOT NULL DEFAULT TRUE,
    run_canary                BOOLEAN NOT NULL DEFAULT TRUE,
    run_gates                 BOOLEAN NOT NULL DEFAULT TRUE,
    run_benchmarks            BOOLEAN NOT NULL DEFAULT FALSE,
    full_market               BOOLEAN NOT NULL DEFAULT FALSE,
    live_base_url_env         VARCHAR(128) NOT NULL DEFAULT 'QDATA_VENDOR_BASE_URL',
    live_token_env            VARCHAR(128) NOT NULL DEFAULT 'QDATA_VENDOR_TOKEN',
    live_base_url_present     BOOLEAN NOT NULL DEFAULT FALSE,
    live_token_present        BOOLEAN NOT NULL DEFAULT FALSE,
    auth_mode                 VARCHAR(32),
    profile_status            VARCHAR(24),
    contract_status           VARCHAR(32) NOT NULL DEFAULT 'unknown',
    redistribution_allowed    BOOLEAN,
    rate_limit_per_min        INTEGER,
    gate_ids                  BIGINT[] NOT NULL DEFAULT '{}',
    gate_codes                TEXT[] NOT NULL DEFAULT '{}',
    blocking_issues           TEXT[] NOT NULL DEFAULT '{}',
    next_actions              TEXT[] NOT NULL DEFAULT '{}',
    request_payload           JSONB NOT NULL DEFAULT '{}'::jsonb,
    response_payload          JSONB NOT NULL DEFAULT '{}'::jsonb,
    evidence                  JSONB NOT NULL DEFAULT '{}'::jsonb,
    error_message             TEXT,
    started_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at               TIMESTAMPTZ,
    duration_ms               INTEGER,
    created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (trigger_mode IN ('manual', 'scheduled', 'api', 'smoke', 'demo')),
    CHECK (status IN ('planned', 'success', 'warning', 'failed', 'blocked', 'skipped')),
    CHECK (preflight_status IN ('planned', 'success', 'warning', 'failed', 'blocked', 'skipped')),
    CHECK (canary_status IN ('planned', 'success', 'warning', 'failed', 'blocked', 'skipped')),
    CHECK (gate_status IN ('planned', 'success', 'warning', 'failed', 'blocked', 'skipped')),
    CHECK (orchestration_status IN ('planned', 'success', 'warning', 'failed', 'blocked', 'skipped')),
    CHECK (recommendation IN ('reject', 'research_only', 'backup', 'primary_candidate')),
    CHECK (recommended_role IN ('reject', 'research_only', 'backup', 'primary_candidate')),
    CHECK (array_length(dataset_codes, 1) IS NOT NULL),
    CHECK (array_length(required_windows, 1) IS NOT NULL),
    CHECK (shard_size > 0),
    CHECK (max_symbols IS NULL OR max_symbols > 0),
    CHECK (rate_limit_per_min IS NULL OR rate_limit_per_min > 0)
);

CREATE TABLE IF NOT EXISTS qmeta.vendor_onboarding_dataset_result (
    result_id                 BIGSERIAL PRIMARY KEY,
    run_id                    BIGINT NOT NULL REFERENCES qmeta.vendor_onboarding_run(run_id) ON DELETE CASCADE,
    dataset_id                BIGINT NOT NULL REFERENCES qmeta.dataset_catalog(dataset_id),
    source_id                 BIGINT NOT NULL REFERENCES qmeta.source_system(source_id),
    primary_source_id         BIGINT REFERENCES qmeta.source_system(source_id),
    gate_id                   BIGINT REFERENCES qmeta.vendor_live_gate_run(gate_id) ON DELETE SET NULL,
    stage_status              VARCHAR(32) NOT NULL DEFAULT 'planned',
    preflight_status          VARCHAR(32) NOT NULL DEFAULT 'planned',
    canary_status             VARCHAR(32) NOT NULL DEFAULT 'planned',
    gate_status               VARCHAR(32) NOT NULL DEFAULT 'planned',
    recommendation            VARCHAR(32) NOT NULL DEFAULT 'research_only',
    recommended_role          VARCHAR(32) NOT NULL DEFAULT 'research_only',
    required_windows          INTEGER[] NOT NULL DEFAULT ARRAY[5, 20, 60],
    executed_windows          INTEGER[] NOT NULL DEFAULT '{}',
    shard_size                INTEGER NOT NULL DEFAULT 500,
    max_symbols               INTEGER,
    symbol_count              BIGINT,
    live_requested            BOOLEAN NOT NULL DEFAULT FALSE,
    live_executed             BOOLEAN NOT NULL DEFAULT FALSE,
    blocking_issues           TEXT[] NOT NULL DEFAULT '{}',
    next_actions              TEXT[] NOT NULL DEFAULT '{}',
    evidence                  JSONB NOT NULL DEFAULT '{}'::jsonb,
    error_message             TEXT,
    started_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at               TIMESTAMPTZ,
    duration_ms               INTEGER,
    created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (run_id, dataset_id),
    CHECK (stage_status IN ('planned', 'success', 'warning', 'failed', 'blocked', 'skipped')),
    CHECK (preflight_status IN ('planned', 'success', 'warning', 'failed', 'blocked', 'skipped')),
    CHECK (canary_status IN ('planned', 'success', 'warning', 'failed', 'blocked', 'skipped')),
    CHECK (gate_status IN ('planned', 'success', 'warning', 'failed', 'blocked', 'skipped')),
    CHECK (recommendation IN ('reject', 'research_only', 'backup', 'primary_candidate')),
    CHECK (recommended_role IN ('reject', 'research_only', 'backup', 'primary_candidate')),
    CHECK (array_length(required_windows, 1) IS NOT NULL),
    CHECK (shard_size > 0),
    CHECK (max_symbols IS NULL OR max_symbols > 0),
    CHECK (symbol_count IS NULL OR symbol_count >= 0)
);

CREATE INDEX IF NOT EXISTS idx_vendor_onboarding_run_lookup
    ON qmeta.vendor_onboarding_run(source_id, started_at DESC, status);

CREATE INDEX IF NOT EXISTS idx_vendor_onboarding_run_status
    ON qmeta.vendor_onboarding_run(status, recommendation, started_at DESC);

CREATE INDEX IF NOT EXISTS idx_vendor_onboarding_dataset_lookup
    ON qmeta.vendor_onboarding_dataset_result(run_id, dataset_id, stage_status);

CREATE INDEX IF NOT EXISTS idx_vendor_onboarding_dataset_status
    ON qmeta.vendor_onboarding_dataset_result(stage_status, gate_status, started_at DESC);
