-- A 股量化数据平台 Eta-3：真实供应商 Live 接入闭环

CREATE TABLE IF NOT EXISTS qmeta.vendor_live_closure_run (
    closure_id                BIGSERIAL PRIMARY KEY,
    closure_code              VARCHAR(180) NOT NULL UNIQUE,
    source_id                 BIGINT NOT NULL REFERENCES qmeta.source_system(source_id),
    profile_id                BIGINT REFERENCES qmeta.vendor_integration_profile(profile_id) ON DELETE SET NULL,
    primary_source_id         BIGINT REFERENCES qmeta.source_system(source_id),
    onboarding_run_id         BIGINT REFERENCES qmeta.vendor_onboarding_run(run_id) ON DELETE SET NULL,
    requested_by              VARCHAR(128) NOT NULL DEFAULT 'eta3',
    trigger_mode              VARCHAR(32) NOT NULL DEFAULT 'manual',
    environment               VARCHAR(32) NOT NULL DEFAULT 'local',
    status                    VARCHAR(32) NOT NULL DEFAULT 'planned',
    config_status             VARCHAR(32) NOT NULL DEFAULT 'planned',
    profile_check_status      VARCHAR(32) NOT NULL DEFAULT 'planned',
    profile_update_status     VARCHAR(32) NOT NULL DEFAULT 'skipped',
    contract_status           VARCHAR(32) NOT NULL DEFAULT 'unknown',
    endpoint_status           VARCHAR(32) NOT NULL DEFAULT 'planned',
    onboarding_status         VARCHAR(32) NOT NULL DEFAULT 'planned',
    promotion_status          VARCHAR(32) NOT NULL DEFAULT 'planned',
    recommendation            VARCHAR(32) NOT NULL DEFAULT 'research_only',
    recommended_role          VARCHAR(32) NOT NULL DEFAULT 'research_only',
    dataset_codes             TEXT[] NOT NULL DEFAULT '{}',
    enabled_dataset_codes     TEXT[] NOT NULL DEFAULT '{}',
    missing_dataset_codes     TEXT[] NOT NULL DEFAULT '{}',
    canary_symbols            TEXT[] NOT NULL DEFAULT '{}',
    required_windows          INTEGER[] NOT NULL DEFAULT ARRAY[5, 20, 60],
    shard_size                INTEGER NOT NULL DEFAULT 500,
    max_symbols               INTEGER,
    allow_live                BOOLEAN NOT NULL DEFAULT FALSE,
    require_live              BOOLEAN NOT NULL DEFAULT FALSE,
    allow_profile_write       BOOLEAN NOT NULL DEFAULT FALSE,
    activate_profile          BOOLEAN NOT NULL DEFAULT FALSE,
    enable_profile_datasets   BOOLEAN NOT NULL DEFAULT FALSE,
    run_endpoint_probes       BOOLEAN NOT NULL DEFAULT TRUE,
    run_onboarding            BOOLEAN NOT NULL DEFAULT TRUE,
    run_benchmarks            BOOLEAN NOT NULL DEFAULT FALSE,
    full_market               BOOLEAN NOT NULL DEFAULT FALSE,
    live_base_url_env         VARCHAR(128) NOT NULL DEFAULT 'QDATA_VENDOR_BASE_URL',
    live_token_env            VARCHAR(128) NOT NULL DEFAULT 'QDATA_VENDOR_TOKEN',
    live_base_url_present     BOOLEAN NOT NULL DEFAULT FALSE,
    live_token_present        BOOLEAN NOT NULL DEFAULT FALSE,
    auth_mode                 VARCHAR(32),
    profile_status            VARCHAR(24),
    profile_contract_ref_present BOOLEAN NOT NULL DEFAULT FALSE,
    redistribution_allowed    BOOLEAN,
    rate_limit_per_min        INTEGER,
    endpoint_probe_count      INTEGER NOT NULL DEFAULT 0,
    endpoint_probe_success_count INTEGER NOT NULL DEFAULT 0,
    endpoint_probe_blocked_count INTEGER NOT NULL DEFAULT 0,
    endpoint_probe_failed_count INTEGER NOT NULL DEFAULT 0,
    onboarding_run_code       VARCHAR(180),
    gate_ids                  BIGINT[] NOT NULL DEFAULT '{}',
    gate_codes                TEXT[] NOT NULL DEFAULT '{}',
    blocking_issues           TEXT[] NOT NULL DEFAULT '{}',
    next_actions              TEXT[] NOT NULL DEFAULT '{}',
    request_payload           JSONB NOT NULL DEFAULT '{}'::jsonb,
    response_payload          JSONB NOT NULL DEFAULT '{}'::jsonb,
    evidence                  JSONB NOT NULL DEFAULT '{}'::jsonb,
    error_message             TEXT,
    started_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at               TIMESTAMPTZ,
    duration_ms               INTEGER,
    created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (trigger_mode IN ('manual', 'scheduled', 'api', 'smoke', 'demo')),
    CHECK (status IN ('planned', 'success', 'warning', 'failed', 'blocked', 'skipped')),
    CHECK (config_status IN ('planned', 'success', 'warning', 'failed', 'blocked', 'skipped')),
    CHECK (profile_check_status IN ('planned', 'success', 'warning', 'failed', 'blocked', 'skipped')),
    CHECK (profile_update_status IN ('planned', 'success', 'warning', 'failed', 'blocked', 'skipped')),
    CHECK (endpoint_status IN ('planned', 'success', 'warning', 'failed', 'blocked', 'skipped')),
    CHECK (onboarding_status IN ('planned', 'success', 'warning', 'failed', 'blocked', 'skipped')),
    CHECK (promotion_status IN ('planned', 'success', 'warning', 'failed', 'blocked', 'skipped')),
    CHECK (contract_status IN ('unknown', 'missing', 'contracted', 'skipped')),
    CHECK (recommendation IN ('reject', 'research_only', 'backup', 'primary_candidate')),
    CHECK (recommended_role IN ('reject', 'research_only', 'backup', 'primary_candidate')),
    CHECK (array_length(dataset_codes, 1) IS NOT NULL),
    CHECK (array_length(required_windows, 1) IS NOT NULL),
    CHECK (shard_size > 0),
    CHECK (max_symbols IS NULL OR max_symbols > 0),
    CHECK (rate_limit_per_min IS NULL OR rate_limit_per_min > 0),
    CHECK (endpoint_probe_count >= 0),
    CHECK (endpoint_probe_success_count >= 0),
    CHECK (endpoint_probe_blocked_count >= 0),
    CHECK (endpoint_probe_failed_count >= 0)
);

CREATE TABLE IF NOT EXISTS qmeta.vendor_live_endpoint_probe (
    probe_id                  BIGSERIAL PRIMARY KEY,
    probe_code                VARCHAR(180) NOT NULL UNIQUE,
    closure_id                BIGINT NOT NULL REFERENCES qmeta.vendor_live_closure_run(closure_id) ON DELETE CASCADE,
    dataset_id                BIGINT NOT NULL REFERENCES qmeta.dataset_catalog(dataset_id),
    source_id                 BIGINT NOT NULL REFERENCES qmeta.source_system(source_id),
    status                    VARCHAR(32) NOT NULL DEFAULT 'planned',
    auth_status               VARCHAR(32) NOT NULL DEFAULT 'planned',
    schema_status             VARCHAR(32) NOT NULL DEFAULT 'planned',
    endpoint_path             VARCHAR(256) NOT NULL,
    method                    VARCHAR(16) NOT NULL DEFAULT 'GET',
    live_requested            BOOLEAN NOT NULL DEFAULT FALSE,
    live_executed             BOOLEAN NOT NULL DEFAULT FALSE,
    http_status_code          INTEGER,
    row_count                 INTEGER,
    expected_fields           TEXT[] NOT NULL DEFAULT '{}',
    observed_fields           TEXT[] NOT NULL DEFAULT '{}',
    missing_fields            TEXT[] NOT NULL DEFAULT '{}',
    latency_ms                INTEGER,
    request_payload           JSONB NOT NULL DEFAULT '{}'::jsonb,
    response_payload          JSONB NOT NULL DEFAULT '{}'::jsonb,
    evidence                  JSONB NOT NULL DEFAULT '{}'::jsonb,
    error_message             TEXT,
    started_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at               TIMESTAMPTZ,
    duration_ms               INTEGER,
    created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (status IN ('planned', 'success', 'warning', 'failed', 'blocked', 'skipped')),
    CHECK (auth_status IN ('planned', 'success', 'warning', 'failed', 'blocked', 'skipped')),
    CHECK (schema_status IN ('planned', 'success', 'warning', 'failed', 'blocked', 'skipped')),
    CHECK (method IN ('GET', 'POST')),
    CHECK (http_status_code IS NULL OR http_status_code >= 100),
    CHECK (row_count IS NULL OR row_count >= 0),
    CHECK (latency_ms IS NULL OR latency_ms >= 0)
);

CREATE INDEX IF NOT EXISTS idx_vendor_live_closure_lookup
    ON qmeta.vendor_live_closure_run(source_id, started_at DESC, status);

CREATE INDEX IF NOT EXISTS idx_vendor_live_closure_status
    ON qmeta.vendor_live_closure_run(status, recommendation, started_at DESC);

CREATE INDEX IF NOT EXISTS idx_vendor_live_probe_closure
    ON qmeta.vendor_live_endpoint_probe(closure_id, dataset_id, status);

CREATE INDEX IF NOT EXISTS idx_vendor_live_probe_status
    ON qmeta.vendor_live_endpoint_probe(status, schema_status, started_at DESC);
