-- A 股量化数据平台 Theta-3：真实供应商 Live Pilot 试运行

CREATE TABLE IF NOT EXISTS qmeta.vendor_live_pilot_run (
    pilot_id                 BIGSERIAL PRIMARY KEY,
    pilot_code               VARCHAR(180) NOT NULL UNIQUE,
    source_id                BIGINT NOT NULL REFERENCES qmeta.source_system(source_id),
    primary_source_id        BIGINT REFERENCES qmeta.source_system(source_id),
    closure_id               BIGINT REFERENCES qmeta.vendor_live_closure_run(closure_id) ON DELETE SET NULL,
    closure_code             VARCHAR(180),
    requested_by             VARCHAR(128) NOT NULL DEFAULT 'theta3',
    trigger_mode             VARCHAR(32) NOT NULL DEFAULT 'manual',
    environment              VARCHAR(32) NOT NULL DEFAULT 'local',
    pilot_scope              VARCHAR(32) NOT NULL DEFAULT 'canary',
    status                   VARCHAR(32) NOT NULL DEFAULT 'planned',
    closure_status           VARCHAR(32) NOT NULL DEFAULT 'planned',
    endpoint_status          VARCHAR(32) NOT NULL DEFAULT 'planned',
    onboarding_status        VARCHAR(32) NOT NULL DEFAULT 'planned',
    benchmark_status         VARCHAR(32) NOT NULL DEFAULT 'skipped',
    signoff_status           VARCHAR(32) NOT NULL DEFAULT 'not_ready',
    recommendation           VARCHAR(32) NOT NULL DEFAULT 'research_only',
    recommended_role         VARCHAR(32) NOT NULL DEFAULT 'research_only',
    risk_level               VARCHAR(16) NOT NULL DEFAULT 'unknown',
    dataset_codes            TEXT[] NOT NULL DEFAULT '{}',
    canary_symbols           TEXT[] NOT NULL DEFAULT '{}',
    required_windows         INTEGER[] NOT NULL DEFAULT ARRAY[5, 20, 60],
    shard_size               INTEGER NOT NULL DEFAULT 500,
    max_symbols              INTEGER,
    allow_live               BOOLEAN NOT NULL DEFAULT FALSE,
    require_live             BOOLEAN NOT NULL DEFAULT FALSE,
    run_endpoint_probes      BOOLEAN NOT NULL DEFAULT TRUE,
    run_onboarding           BOOLEAN NOT NULL DEFAULT TRUE,
    run_benchmarks           BOOLEAN NOT NULL DEFAULT FALSE,
    full_market              BOOLEAN NOT NULL DEFAULT FALSE,
    live_base_url_present    BOOLEAN NOT NULL DEFAULT FALSE,
    live_token_present       BOOLEAN NOT NULL DEFAULT FALSE,
    dataset_result_count     INTEGER NOT NULL DEFAULT 0,
    dataset_success_count    INTEGER NOT NULL DEFAULT 0,
    dataset_warning_count    INTEGER NOT NULL DEFAULT 0,
    dataset_blocked_count    INTEGER NOT NULL DEFAULT 0,
    dataset_failed_count     INTEGER NOT NULL DEFAULT 0,
    blocking_issues          TEXT[] NOT NULL DEFAULT '{}',
    next_actions             TEXT[] NOT NULL DEFAULT '{}',
    request_payload          JSONB NOT NULL DEFAULT '{}'::jsonb,
    response_payload         JSONB NOT NULL DEFAULT '{}'::jsonb,
    evidence                 JSONB NOT NULL DEFAULT '{}'::jsonb,
    error_message            TEXT,
    started_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at              TIMESTAMPTZ,
    duration_ms              INTEGER,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (trigger_mode IN ('manual', 'scheduled', 'api', 'smoke', 'demo')),
    CHECK (pilot_scope IN ('canary', 'full_market')),
    CHECK (status IN ('planned', 'success', 'warning', 'failed', 'blocked', 'skipped')),
    CHECK (closure_status IN ('planned', 'success', 'warning', 'failed', 'blocked', 'skipped')),
    CHECK (endpoint_status IN ('planned', 'success', 'warning', 'failed', 'blocked', 'skipped')),
    CHECK (onboarding_status IN ('planned', 'success', 'warning', 'failed', 'blocked', 'skipped')),
    CHECK (benchmark_status IN ('planned', 'success', 'warning', 'failed', 'blocked', 'skipped')),
    CHECK (signoff_status IN ('not_ready', 'pending_review', 'approved', 'rejected', 'skipped')),
    CHECK (recommendation IN ('reject', 'research_only', 'backup', 'primary_candidate')),
    CHECK (recommended_role IN ('reject', 'research_only', 'backup', 'primary_candidate')),
    CHECK (risk_level IN ('unknown', 'low', 'medium', 'high', 'critical')),
    CHECK (array_length(dataset_codes, 1) IS NOT NULL),
    CHECK (array_length(required_windows, 1) IS NOT NULL),
    CHECK (shard_size > 0),
    CHECK (max_symbols IS NULL OR max_symbols > 0),
    CHECK (dataset_result_count >= 0),
    CHECK (dataset_success_count >= 0),
    CHECK (dataset_warning_count >= 0),
    CHECK (dataset_blocked_count >= 0),
    CHECK (dataset_failed_count >= 0)
);

CREATE TABLE IF NOT EXISTS qmeta.vendor_live_pilot_dataset_result (
    result_id                BIGSERIAL PRIMARY KEY,
    result_code              VARCHAR(180) NOT NULL UNIQUE,
    pilot_id                 BIGINT NOT NULL REFERENCES qmeta.vendor_live_pilot_run(pilot_id) ON DELETE CASCADE,
    dataset_id               BIGINT NOT NULL REFERENCES qmeta.dataset_catalog(dataset_id),
    source_id                BIGINT NOT NULL REFERENCES qmeta.source_system(source_id),
    closure_id               BIGINT REFERENCES qmeta.vendor_live_closure_run(closure_id) ON DELETE SET NULL,
    probe_code               VARCHAR(180),
    gate_code                VARCHAR(180),
    status                   VARCHAR(32) NOT NULL DEFAULT 'planned',
    closure_status           VARCHAR(32) NOT NULL DEFAULT 'planned',
    endpoint_status          VARCHAR(32) NOT NULL DEFAULT 'planned',
    schema_status            VARCHAR(32) NOT NULL DEFAULT 'planned',
    onboarding_status        VARCHAR(32) NOT NULL DEFAULT 'planned',
    gate_status              VARCHAR(32) NOT NULL DEFAULT 'planned',
    benchmark_status         VARCHAR(32) NOT NULL DEFAULT 'skipped',
    recommendation           VARCHAR(32) NOT NULL DEFAULT 'research_only',
    recommended_role         VARCHAR(32) NOT NULL DEFAULT 'research_only',
    risk_level               VARCHAR(16) NOT NULL DEFAULT 'unknown',
    live_requested           BOOLEAN NOT NULL DEFAULT FALSE,
    live_executed            BOOLEAN NOT NULL DEFAULT FALSE,
    row_count                INTEGER,
    missing_fields           TEXT[] NOT NULL DEFAULT '{}',
    blocking_issues          TEXT[] NOT NULL DEFAULT '{}',
    next_actions             TEXT[] NOT NULL DEFAULT '{}',
    evidence                 JSONB NOT NULL DEFAULT '{}'::jsonb,
    error_message            TEXT,
    started_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at              TIMESTAMPTZ,
    duration_ms              INTEGER,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (status IN ('planned', 'success', 'warning', 'failed', 'blocked', 'skipped')),
    CHECK (closure_status IN ('planned', 'success', 'warning', 'failed', 'blocked', 'skipped')),
    CHECK (endpoint_status IN ('planned', 'success', 'warning', 'failed', 'blocked', 'skipped')),
    CHECK (schema_status IN ('planned', 'success', 'warning', 'failed', 'blocked', 'skipped')),
    CHECK (onboarding_status IN ('planned', 'success', 'warning', 'failed', 'blocked', 'skipped')),
    CHECK (gate_status IN ('planned', 'success', 'warning', 'failed', 'blocked', 'skipped')),
    CHECK (benchmark_status IN ('planned', 'success', 'warning', 'failed', 'blocked', 'skipped')),
    CHECK (recommendation IN ('reject', 'research_only', 'backup', 'primary_candidate')),
    CHECK (recommended_role IN ('reject', 'research_only', 'backup', 'primary_candidate')),
    CHECK (risk_level IN ('unknown', 'low', 'medium', 'high', 'critical')),
    CHECK (row_count IS NULL OR row_count >= 0)
);

CREATE INDEX IF NOT EXISTS idx_vendor_live_pilot_lookup
    ON qmeta.vendor_live_pilot_run(source_id, started_at DESC, status);

CREATE INDEX IF NOT EXISTS idx_vendor_live_pilot_status
    ON qmeta.vendor_live_pilot_run(status, signoff_status, started_at DESC);

CREATE INDEX IF NOT EXISTS idx_vendor_live_pilot_result_lookup
    ON qmeta.vendor_live_pilot_dataset_result(pilot_id, dataset_id, status);

CREATE INDEX IF NOT EXISTS idx_vendor_live_pilot_result_status
    ON qmeta.vendor_live_pilot_dataset_result(status, risk_level, started_at DESC);
