-- A 股量化数据平台 Iota-3：免费源联盟 Free Source Fabric

INSERT INTO qmeta.source_system (
    source_code, source_name, source_type, license_scope, update_frequency, latency_level, owner
) VALUES
    ('csv', '本地 CSV 免费源 smoke', 'internal', 'local smoke fixture only', 'daily', 'L4', 'qdata'),
    ('csv_mirror', '本地 CSV 镜像免费源 smoke', 'internal', 'local mirror fixture only', 'daily', 'L4', 'qdata'),
    ('akshare', 'AKShare 开源财经数据接口', 'other', 'free/open-source public web aggregation; verify upstream terms before commercial use', 'daily', 'L3', 'qdata'),
    ('baostock', 'BaoStock 免费证券数据平台', 'other', 'free/open-source research source; verify redistribution terms', 'daily', 'L4', 'qdata'),
    ('tushare_free', 'TuShare Pro 免费积分档', 'vendor', 'free quota/token tier; commercial and frequency limits require review', 'daily', 'L3', 'qdata'),
    ('cninfo_public', '巨潮资讯公开公告', 'announcement', 'public announcement pages; cache and redistribution terms require review', 'intraday', 'L3', 'qdata'),
    ('sse_public', '上交所公开数据', 'exchange', 'official public exchange pages; reuse terms require review', 'daily', 'L3', 'qdata'),
    ('szse_public', '深交所公开数据', 'exchange', 'official public exchange pages; reuse terms require review', 'daily', 'L3', 'qdata'),
    ('nbs_public', '国家统计局公开数据', 'other', 'official public macro data; reuse terms require review', 'monthly', 'L4', 'qdata')
ON CONFLICT (source_code) DO UPDATE SET
    source_name = EXCLUDED.source_name,
    source_type = EXCLUDED.source_type,
    license_scope = EXCLUDED.license_scope,
    update_frequency = EXCLUDED.update_frequency,
    latency_level = EXCLUDED.latency_level,
    owner = EXCLUDED.owner,
    updated_at = now();

CREATE TABLE IF NOT EXISTS qmeta.free_source_fabric_run (
    fabric_id                       BIGSERIAL PRIMARY KEY,
    fabric_code                     VARCHAR(180) NOT NULL UNIQUE,
    requested_by                    VARCHAR(128) NOT NULL DEFAULT 'iota3',
    trigger_mode                    VARCHAR(32) NOT NULL DEFAULT 'manual',
    environment                     VARCHAR(32) NOT NULL DEFAULT 'local',
    fabric_scope                    VARCHAR(32) NOT NULL DEFAULT 'canary',
    status                          VARCHAR(32) NOT NULL DEFAULT 'planned',
    recommendation                  VARCHAR(32) NOT NULL DEFAULT 'research_only',
    recommended_role                VARCHAR(32) NOT NULL DEFAULT 'research_only',
    risk_level                      VARCHAR(16) NOT NULL DEFAULT 'unknown',
    baseline_source_code            VARCHAR(64),
    dataset_codes                   TEXT[] NOT NULL DEFAULT '{}',
    source_codes                    TEXT[] NOT NULL DEFAULT '{}',
    canary_symbols                  TEXT[] NOT NULL DEFAULT '{}',
    start_date                      DATE NOT NULL,
    end_date                        DATE NOT NULL,
    allow_external                  BOOLEAN NOT NULL DEFAULT FALSE,
    require_external                BOOLEAN NOT NULL DEFAULT FALSE,
    require_commercial_clearance    BOOLEAN NOT NULL DEFAULT FALSE,
    min_source_count                INTEGER NOT NULL DEFAULT 2,
    min_coverage_rate               NUMERIC(10, 6) NOT NULL DEFAULT 0.950000,
    max_conflict_rate_bps           NUMERIC(18, 6) NOT NULL DEFAULT 5.000000,
    source_count                    INTEGER NOT NULL DEFAULT 0,
    executable_source_count         INTEGER NOT NULL DEFAULT 0,
    external_source_count           INTEGER NOT NULL DEFAULT 0,
    usable_source_count             INTEGER NOT NULL DEFAULT 0,
    dataset_result_count            INTEGER NOT NULL DEFAULT 0,
    dataset_success_count           INTEGER NOT NULL DEFAULT 0,
    dataset_warning_count           INTEGER NOT NULL DEFAULT 0,
    dataset_blocked_count           INTEGER NOT NULL DEFAULT 0,
    dataset_failed_count            INTEGER NOT NULL DEFAULT 0,
    license_review_required_count   INTEGER NOT NULL DEFAULT 0,
    commercial_blocker_count        INTEGER NOT NULL DEFAULT 0,
    coverage_rate                   NUMERIC(10, 6),
    conflict_rate_bps               NUMERIC(18, 6),
    blocking_issues                 TEXT[] NOT NULL DEFAULT '{}',
    next_actions                    TEXT[] NOT NULL DEFAULT '{}',
    request_payload                 JSONB NOT NULL DEFAULT '{}'::jsonb,
    response_payload                JSONB NOT NULL DEFAULT '{}'::jsonb,
    evidence                        JSONB NOT NULL DEFAULT '{}'::jsonb,
    error_message                   TEXT,
    started_at                      TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at                     TIMESTAMPTZ,
    duration_ms                     INTEGER,
    created_at                      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (trigger_mode IN ('manual', 'scheduled', 'api', 'smoke', 'demo')),
    CHECK (fabric_scope IN ('canary', 'full_market')),
    CHECK (status IN ('planned', 'success', 'warning', 'failed', 'blocked', 'skipped')),
    CHECK (recommendation IN ('reject', 'research_only', 'backup', 'primary_candidate')),
    CHECK (recommended_role IN ('reject', 'research_only', 'backup', 'primary_candidate')),
    CHECK (risk_level IN ('unknown', 'low', 'medium', 'high', 'critical')),
    CHECK (array_length(dataset_codes, 1) IS NOT NULL),
    CHECK (array_length(source_codes, 1) IS NOT NULL),
    CHECK (start_date <= end_date),
    CHECK (min_source_count > 0),
    CHECK (min_coverage_rate >= 0 AND min_coverage_rate <= 1),
    CHECK (max_conflict_rate_bps >= 0),
    CHECK (source_count >= 0),
    CHECK (executable_source_count >= 0),
    CHECK (external_source_count >= 0),
    CHECK (usable_source_count >= 0),
    CHECK (dataset_result_count >= 0),
    CHECK (dataset_success_count >= 0),
    CHECK (dataset_warning_count >= 0),
    CHECK (dataset_blocked_count >= 0),
    CHECK (dataset_failed_count >= 0),
    CHECK (license_review_required_count >= 0),
    CHECK (commercial_blocker_count >= 0),
    CHECK (coverage_rate IS NULL OR (coverage_rate >= 0 AND coverage_rate <= 1)),
    CHECK (conflict_rate_bps IS NULL OR conflict_rate_bps >= 0)
);

CREATE TABLE IF NOT EXISTS qmeta.free_source_fabric_dataset_result (
    result_id                       BIGSERIAL PRIMARY KEY,
    result_code                     VARCHAR(180) NOT NULL UNIQUE,
    fabric_id                       BIGINT NOT NULL REFERENCES qmeta.free_source_fabric_run(fabric_id) ON DELETE CASCADE,
    dataset_id                      BIGINT NOT NULL REFERENCES qmeta.dataset_catalog(dataset_id),
    status                          VARCHAR(32) NOT NULL DEFAULT 'planned',
    coverage_status                 VARCHAR(32) NOT NULL DEFAULT 'planned',
    consistency_status              VARCHAR(32) NOT NULL DEFAULT 'planned',
    license_status                  VARCHAR(32) NOT NULL DEFAULT 'unknown',
    freshness_status                VARCHAR(32) NOT NULL DEFAULT 'planned',
    recommendation                  VARCHAR(32) NOT NULL DEFAULT 'research_only',
    recommended_role                VARCHAR(32) NOT NULL DEFAULT 'research_only',
    risk_level                      VARCHAR(16) NOT NULL DEFAULT 'unknown',
    baseline_source_code            VARCHAR(64),
    source_codes                    TEXT[] NOT NULL DEFAULT '{}',
    executed_sources                TEXT[] NOT NULL DEFAULT '{}',
    blocked_sources                 TEXT[] NOT NULL DEFAULT '{}',
    missing_sources                 TEXT[] NOT NULL DEFAULT '{}',
    license_blocking_sources        TEXT[] NOT NULL DEFAULT '{}',
    source_count                    INTEGER NOT NULL DEFAULT 0,
    usable_source_count             INTEGER NOT NULL DEFAULT 0,
    expected_row_count              INTEGER,
    baseline_row_count              INTEGER,
    row_count                       INTEGER,
    coverage_rate                   NUMERIC(10, 6),
    conflict_rate_bps               NUMERIC(18, 6),
    max_abs_value_diff              NUMERIC(28, 10),
    blocking_issues                 TEXT[] NOT NULL DEFAULT '{}',
    next_actions                    TEXT[] NOT NULL DEFAULT '{}',
    evidence                        JSONB NOT NULL DEFAULT '{}'::jsonb,
    error_message                   TEXT,
    started_at                      TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at                     TIMESTAMPTZ,
    duration_ms                     INTEGER,
    created_at                      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (status IN ('planned', 'success', 'warning', 'failed', 'blocked', 'skipped')),
    CHECK (coverage_status IN ('planned', 'success', 'warning', 'failed', 'blocked', 'skipped')),
    CHECK (consistency_status IN ('planned', 'success', 'warning', 'failed', 'blocked', 'skipped')),
    CHECK (freshness_status IN ('planned', 'success', 'warning', 'failed', 'blocked', 'skipped')),
    CHECK (license_status IN ('unknown', 'local_smoke', 'official_public', 'research_only', 'review_required', 'blocked')),
    CHECK (recommendation IN ('reject', 'research_only', 'backup', 'primary_candidate')),
    CHECK (recommended_role IN ('reject', 'research_only', 'backup', 'primary_candidate')),
    CHECK (risk_level IN ('unknown', 'low', 'medium', 'high', 'critical')),
    CHECK (source_count >= 0),
    CHECK (usable_source_count >= 0),
    CHECK (expected_row_count IS NULL OR expected_row_count >= 0),
    CHECK (baseline_row_count IS NULL OR baseline_row_count >= 0),
    CHECK (row_count IS NULL OR row_count >= 0),
    CHECK (coverage_rate IS NULL OR (coverage_rate >= 0 AND coverage_rate <= 1)),
    CHECK (conflict_rate_bps IS NULL OR conflict_rate_bps >= 0),
    CHECK (max_abs_value_diff IS NULL OR max_abs_value_diff >= 0)
);

CREATE INDEX IF NOT EXISTS idx_free_source_fabric_run_lookup
    ON qmeta.free_source_fabric_run(started_at DESC, status, fabric_scope);

CREATE INDEX IF NOT EXISTS idx_free_source_fabric_run_status
    ON qmeta.free_source_fabric_run(status, recommendation, risk_level, started_at DESC);

CREATE INDEX IF NOT EXISTS idx_free_source_fabric_result_lookup
    ON qmeta.free_source_fabric_dataset_result(fabric_id, dataset_id, status);

CREATE INDEX IF NOT EXISTS idx_free_source_fabric_result_status
    ON qmeta.free_source_fabric_dataset_result(status, license_status, risk_level, started_at DESC);
