-- DEPRECATED: this legacy aggregate DDL is intentionally non-executable.
--
-- Canonical fresh-install schemas:
--   PostgreSQL: db/migrations/0001_postgresql_init.sql
--   ClickHouse: db/migrations/0002_clickhouse_init.sql
--
-- Existing deployments must apply the forward-only, engine-specific files in
-- db/migrations/.  db/table.sql is a cross-engine reference snapshot for human
-- review and schema contract tests; it is not a migration entrypoint.
