-- A 股量化数据底座 MVP 增量变更脚本
-- 当前版本为全新初始化，暂无增量变更。
-- 后续兼容性变更在此文件追加，禁止直接修改已发布迁移脚本。

-- Example:
-- ALTER TABLE qmeta.dataset_catalog ADD COLUMN IF NOT EXISTS owner_team VARCHAR(128);

\i db/migrations/0003_postgresql_pipeline_scheduler.sql
\i db/migrations/0004_postgresql_full_market_pipeline.sql
\i db/migrations/0005_postgresql_production_gamma.sql
\i db/migrations/0006_postgresql_quant_market_delta.sql
\i db/migrations/0007_postgresql_service_fusion_epsilon.sql
\i db/migrations/0008_postgresql_ops_zeta.sql
\i db/migrations/0009_postgresql_vendor_eta.sql
\i db/migrations/0010_postgresql_vendor_theta.sql
\i db/migrations/0011_postgresql_ops_iota.sql
\i db/migrations/0012_postgresql_ops_lambda.sql
\i db/migrations/0013_postgresql_ops_mu.sql
\i db/migrations/0014_postgresql_ops_nu.sql
\i db/migrations/0015_postgresql_product_xi.sql
\i db/migrations/0016_postgresql_billing_omicron.sql
\i db/migrations/0017_postgresql_vendor_pi.sql
\i db/migrations/0018_postgresql_revenue_rho.sql
\i db/migrations/0019_postgresql_runtime_sigma.sql
\i db/migrations/0020_postgresql_payments_tau.sql
\i db/migrations/0021_postgresql_strategy_phi.sql
\i db/migrations/0022_postgresql_governance_chi.sql
\i db/migrations/0023_postgresql_automation_psi.sql
\i db/migrations/0024_postgresql_automation_omega.sql
\i db/migrations/0025_postgresql_automation_alpha2.sql
\i db/migrations/0026_postgresql_automation_beta2.sql
\i db/migrations/0027_postgresql_automation_gamma2.sql
\i db/migrations/0028_postgresql_automation_delta2.sql
\i db/migrations/0029_postgresql_vendor_epsilon3_live_gate.sql
\i db/migrations/0030_postgresql_vendor_zeta3_onboarding.sql
\i db/migrations/0031_postgresql_vendor_eta3_live_closure.sql
\i db/migrations/0032_postgresql_vendor_theta3_live_pilot.sql
\i db/migrations/0033_postgresql_free_source_iota3_fabric.sql
\i db/migrations/0034_postgresql_free_source_kappa5_reliability.sql
\i db/migrations/0035_postgresql_free_source_lambda5_recovery.sql
\i db/migrations/0036_postgresql_free_source_mu5_recovery_execution.sql
\i db/migrations/0037_postgresql_free_source_nu5_recovery_health.sql
\i db/migrations/0038_postgresql_free_source_xi5_admission.sql
\i db/migrations/0039_postgresql_vendor_omicron5_contract.sql
\i db/migrations/0040_postgresql_vendor_pi5_primary_promotion.sql
\i db/migrations/0041_postgresql_vendor_rho5_post_promotion_monitor.sql
\i db/migrations/0042_postgresql_vendor_sigma5_primary_stability.sql
\i db/migrations/0043_postgresql_vendor_tau5_cost_optimization.sql
\i db/migrations/0044_postgresql_vendor_upsilon5_route_execution.sql
\i db/migrations/0045_postgresql_vendor_phi5_route_policy_runtime.sql
\i db/migrations/0046_postgresql_vendor_chi5_route_feedback.sql
\i db/migrations/0047_postgresql_automation_psi5_route_incident.sql
\i db/migrations/0048_postgresql_automation_omega5_route_incident_control.sql
\i db/migrations/0049_postgresql_automation_alpha6_route_incident_control_health.sql
\i db/migrations/0050_postgresql_automation_beta6_route_incident_operations.sql
\i db/migrations/0051_postgresql_automation_gamma6_route_incident_approval_api.sql
\i db/migrations/0052_postgresql_automation_delta6_route_incident_approval_governance.sql
\i db/migrations/0053_postgresql_automation_epsilon6_route_incident_approval_resilience.sql
\i db/migrations/0054_postgresql_automation_zeta6_route_incident_approval_release.sql
\i db/migrations/0055_postgresql_vendor_eta6_production_source_closure.sql
